name: MediDoc
description: medidoc project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  get: ^3.25.6
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: "^0.16.0+1"
  google_sign_in: ^4.5.1
  adobe_xd: ^1.1.0+1
  cached_network_image: ^2.5.0
  material_floating_search_bar: ^0.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/stethoscope.png
    - assets/images/image 1.png
    - assets/images/image 3.png
    - assets/images/image 4.png
    - assets/images/image 5.png
