name: medidoc
description: medidoc project

publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  get: ^4.1.4
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  google_sign_in: ^5.0.4
  adobe_xd: ^2.0.0+1
  cached_network_image: ^3.0.0
  simple_search_bar: ^0.1.7
  payhere_mobilesdk_flutter: ^1.0.2
  qrscan: ^0.3.1
  qr_flutter: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/stethoscope.png
    - assets/images/image 1.png
    - assets/images/image 3.png
    - assets/images/image 4.png
    - assets/images/image 5.png
